{
 "title": "Triton Inference Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_inference_request_success{model=\"image_classifier\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_inference_request_failure{model=\"image_classifier\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Requests (Queue)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "nv_inference_pending_request_count{model=\"image_classifier\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  rate(nv_inference_request_duration_us_bucket{model=\"image_classifier\"}[1m])\r\n)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  rate(nv_inference_request_duration_us_bucket{model=\"image_classifier\"}[1m])\r\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  rate(nv_inference_request_duration_us_bucket{model=\"image_classifier\"}[1m])\r\n)",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(nv_inference_request_success{model=\"image_classifier\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(nv_inference_request_failure{model=\"image_classifier\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}